### ISSUE TITLE
ImportEror: No module named nmap

### ISSUE THREAD

**Issue by Cyb3rW1z4rd** [mikaelkall/massrecon#1]
I did a 
pip install python-nmap and
apt-get install python-nmap

but i still get the error:
python ./massrecon.py recon 192.168.0.20
Traceback (most recent call last):
  File "./massrecon.py", line 12, in <module>
    from librecon.librecon import *
  File "/opt/massrecon/librecon/librecon.py", line 10, in <module>
    from librecon.nmap import *
ImportError: No module named nmap

Very very nice project by the way, especially the CherryTree integration is wonderful.

**Update**
python**3** ./massrecon.py recon 192.168.0.20 works but then i get:
➜ fullportscan is not installed

**Comment by mikaelkall** [comment]
Nice to see that other people find this project useful. I build this tool mostly for myself to help me document and recon during a OSCP exam.

First issue may be related to that you installed the nmap module for python2 and the project is intended for python3

This command should give you the correct modules.

```sh
pip3 install -r requirements.txt 
```

The other issue is as I using "develop" branch for experimenting and it changes for day to day 
this branch can have unexpected results. The master branch should always be release-able and stable to use. Nothing wrong to use the develop branch but it is good to know it could have issues as I experiment there and it could be in a broken state. 

The issue you have with fullportscan module is that I created my own portscanner in go for scan all ports as I could not get the speed I expected with nmap and you are missing that tool. 

You can find the tool here 

https://github.com/mikaelkall/OSCP-cheat-sheet/blob/master/tools/static/linux/x86_64/allportscan    

And you need to put it in this location "/usr/bin/fullportscan"

When I merge these changes to master branch the intention was to make that more clear as I understand it is not easy for people to know that else.
