### ISSUE TITLE
Error installing on kali 2020

### ISSUE THREAD

**Issue by jgilgan** [mikaelkall/massrecon#6]
You created an interesting project here!

I tried to install it on the current version of Kali Linux, but it throws an error:

error: six 1.14.0 is installed but six==1.11.0 is required by set([halo])

I know that it is possible to uninstall python-six via apt-get and install the appropriate version through pip3. But when I try this, apt also wants to uninstall a whole bunch of other system-critical packets that I still need.

Is there a way to bypass this issue or update the requirements so your project runs on the current version?

**Comment by mikaelkall** [comment]
Thanks for this report. I have not tested this on Kali 2020.  
Will look into it, but a quick fix if you want to start use the tool probably just bump halo package. Something like this.

`kali@kali:~/dev/massrecon$ sed -i 's/halo==0.0.12/halo==0.0.29/' ./setup.py`

Then install 

`kali@kali:~/dev/massrecon$ sudo python3 setup.py install`

Note you can also use virtualenv if you don't want to touch the OS python packages in Kali. 

Here is the instructions on how to do that.

`kali@kali:~/dev/massrecon$ sudo apt-get -y install virtualenv`
`kali@kali:~/dev/massrecon$ virtualenv --python /usr/bin/python3 /tmp/massrecon_env`
`kali@kali:~/dev/massrecon$ source /tmp/massrecon_env/bin/activate`
`(massrecon_env) kali@kali:~/dev/massrecon$ python setup.py install`

Or just wait and I will fix it probably later this evening.

**Comment by jgilgan** [comment]
Thanks for the quick reply! 
If you are willing to fix the issue I'll wait and give it a go then.

**Comment by mikaelkall** [comment]
Hi, I have now applied a fix.

Some quick instructions on how to use it. 

Start with delete the old repository and clone it again this is to make sure egg and dist folder is cleaned up as will interference with the results else. ( Or you can delete dist build egg folders manually. )

`
git clone https://github.com/mikaelkall/massrecon.git
`

Make sure old halo package is successfully uninstalled before continue.

`
sudo pip3 uninstall halo
`

Install package. 

`
 sudo python3 setup.py install
 `

If everything works as expected you should have the massrecon.py command.
Here is the output from my tests on Kali 2020

 `
 kali@kali:~$ massrecon.py 
Massrecon 1.0.3 ( http://blog.nighter.se/blog/2019/08/13/massrecon-released/ )
Usage: massrecon [OPTIONS]

General Options

       recon  <ip>      Start recon target
       report           Generate OSCP report from CherryTree data.

   [Modules]

        nmap  <ip>      Run nmap module only
        dirb  <ip>      Run dirb module only
       nikto  <ip>      Run nikto module only
         ftp  <ip>      Run ftp module only
      sslyze  <ip>      Run sslyze module only
   quickscan  <ip>      Run quick portscan on all ports.
`

**Comment by jgilgan** [comment]
Awesome! I just installed it successfully too.
Thank you very much for the fix!
